### ISSUE TITLE
Unable to resolve module Button - Hot Reloading

### ISSUE THREAD

**Issue by dicristomanuel** [ptmt/react-native-macos#104]
After running my brand new untouched project from Xcode on macos if I have Hot Reloading enabled I get this error 

![screen shot 2016-08-19 at 12 06 08 pm](https://cloud.githubusercontent.com/assets/11862464/17817891/698020ba-6606-11e6-8bb0-75110fddcbcd.jpg)

The blurred part is username and project folder.

### React versions: 
"react": "15.3.0",
"react-native-macos": "^0.10.0-rc1"

**Comment by matto1990** [comment]
Can you post the part of your code where you are importing the `Button`?

**Comment by ptmt** [comment]
Or as a option, @dicristomanuel could you upload your project on Github?

**Comment by dicristomanuel** [comment]
Hey guys, thanks for your help. I just pushed to Github the project I was talking about. As I was mentioning there is no code from me, I just followed this path: 
- npm install react-native-macos-cli -g
- react-native-macos init MyProject
- cd MyProject
- open macos/MyProject.xcodeproj

The issue appears only when I enable `Hot Reloading`
You can find the repo [here](https://github.com/dicristomanuel/reactMacosTest)

**Comment by matto1990** [comment]
Have you looked into facebook/react-native#4968 and followed the instructions in the error message? Does that not solve the issue?

**Comment by dicristomanuel** [comment]
Yes, followed that couple times but the issue persist.
If I comment out the require for Button it returns the same issue for the next component requested. It seems like the files that return an error are all into the Components folder

**Comment by ptmt** [comment]
`git clone && npm install` your repository, then running Xcode and enable Hot Reloading:

![image](https://cloud.githubusercontent.com/assets/1004115/17835319/57bf48d6-6770-11e6-9a9e-98fde819bdaf.png)
![image](https://cloud.githubusercontent.com/assets/1004115/17835325/9b165836-6770-11e6-816e-15f414bc679f.png)

Does React Native for iOS work for you?

**Comment by ptmt** [comment]
I've managed to reproduce the issue: Debug JS Remotely + Hot Reloading. Working on fix.

**Comment by ptmt** [comment]
Fixed in `0.10.0-rc3`. Check it out. Hot reloading should be working when you debug your js remotely. There is a problem with applying changes without it now.

**Comment by dicristomanuel** [comment]
Works great man, thanks for your help
