### ISSUE TITLE
PanResponder unable to deal with mouse dragging

### ISSUE THREAD

**Issue by matto1990** [ptmt/react-native-macos#109]
You can see the issue when enabling the `PanResponder` `UIExplorer` example.

This is a critical feature for my application, so I'm going to look into supporting it. @ptmt Do you have any advice or thoughts on how you were going to support it. It seems the card I'd need to change is is `React/Base/RCTTouchHandler.m`.

**Comment by ptmt** [comment]
Yep, https://github.com/ptmt/react-native-macos/blob/master/Examples/UIExplorer/js/ReactARTExample.js (simple svg editor) also is not working. This is related to how React works with events, I'll look into it on a weekend.
