### ISSUE TITLE
Xcode 8 issue in RCTWebSocket

### ISSUE THREAD

**Issue by theneverstill** [ptmt/react-native-macos#115]
Two seemingly easy to fix bugs when updating to Xcode 8:

In RCTWebSocket > RCTSRWebSocket.m:

On two occasions the function is used: SecRandomCopyBytes

Xcode doesn't like that the return value is ignored:

/*!
	@function SecRandomCopyBytes
	@abstract Return count random bytes in *bytes, allocated by the caller.
        It is critical to check the return value for error
	@result Return 0 on success or -1 if something went wrong, check errno
    to find out the real error.
*/

**Comment by theneverstill** [comment]
The actual error: <local path>/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute

**Comment by ptmt** [comment]
What's the version of react-native-macos is this? Tthis error should be fixed in 0.10.0

**Comment by theneverstill** [comment]
Ahh snap, I rolled back after a previous bug and forgot to update after your fix.
