### ISSUE TITLE
Modal onRequestClose not being called

### ISSUE THREAD

**Issue by theneverstill** [ptmt/react-native-macos#116]
I created a modal following the UIExplorer example, but onRequestClose is not being called on close of the modal (via the status bar X button).

**Comment by ptmt** [comment]
Thanks for the issue. Fixed for Window modal. Will rewrite some parts to handle it more correctly.

**Comment by ptmt** [comment]
Published as 0.10.2 to npm

**Comment by theneverstill** [comment]
Thanks!!
