### ISSUE TITLE
Typescript Definition File

### ISSUE THREAD

**Issue by theneverstill** [ptmt/react-native-macos#117]
Feature Request: A typescript definition file

Currently I'm using the following, which is an exact copy of react-native but with the module name changed:
`"react-native-macos": "github:Evernaut/DefinitelyTyped/react-native-macos/react-native-macos.d.ts#64213dd7707b4e9606389a40620f65af79255370"`

It works great, with the following exceptions:
- Module '"react-native-macos"' has no exported member 'Button'.
- Property 'onContentSizeChange' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ScrollViewProps, {} | void>> & ScrollVie...'.
- Module '"react-native-macos"' has no exported member 'NativeEventEmitter'.
- Cannot find module 'EventEmitter'.

(The last item can be mitigated by using an any polyfill.)

**Comment by ptmt** [comment]
You're right, it's 95% the same as RN. Still plenty of work, especially considering you need to keep up with updates. Would you mind to add these definitions to your fork of DefinetlyTyped?

**Comment by theneverstill** [comment]
I've actually never made a ts.d before, so I'll have to spend some time learning how.

**Comment by theneverstill** [comment]
Okay, I updated the definition file. Check the Evernaut repo for the latest commit. I'm not going to submit it to DT since I won't be able to keep it up-to-date/perfect, but I'll leave it where it is and update it as react-native-macos grows so that my compiler doesn't throw errors.

**Comment by ptmt** [comment]
Thank you!
