### ISSUE TITLE
ListView displays in reverse order

### ISSUE THREAD

**Issue by theneverstill** [ptmt/react-native-macos#120]
This can be observed in UIExplorer.

**Comment by knoopx** [comment]
I have been experiencing that same issue since the first time at tried
react native desktop too.

**Comment by theneverstill** [comment]
In /Libraries/CustomComponents/ListView/ListView.js

a) The prop autoScrollToBottom is a misnomer
b) If I switch the order in the "prepend items" section, it appears to render correctly


`if (this.props.autoScrollToBottom) {
  bodyComponents.push(row);
} else {
  bodyComponents = [row].concat(bodyComponents);
}
`

**Comment by ptmt** [comment]
You answered quicker than I have fixed. : ) Yes, this is because of autoScrollToBottom property (there is the other line too with reverse index).

**Comment by ptmt** [comment]
This hack was introduced because ios solution to achieve "chat window reverse order" (translateY: -1) doesn't work well on macOS. It seems broken after a pretty inaccurate merge with latest RN and hasn't got properly tested. Thank you again for reporting.

**Comment by theneverstill** [comment]
I can't even begin to explain how much of a positive performance impact this has made on my app. Now listviews only render rows once. :)

**Comment by ptmt** [comment]
Don't hesitate to open as many issues as you want here and feel free to reach me out in any way. I don't have many hours dedicated to RN macOS right now, but I still have big plans and willing to fix bugs and improve performance. And sometimes a bug can turn out into a simple fix as this : )

**Comment by theneverstill** [comment]
A console.log accidentally got left in the commit/fix.

**Comment by ptmt** [comment]
fixed
