### ISSUE TITLE
Not working with Platform api

### ISSUE THREAD

**Issue by 7kfpun** [ptmt/react-native-macos#123]
It doesn't work with react-native-router-flux and other packages using Platform api. The error is following:
<img width="1045" alt="screen shot 2016-11-06 at 4 23 40 pm" src="https://cloud.githubusercontent.com/assets/2672802/20036245/3072cb26-a43e-11e6-916b-aca886d222b2.png">

- React: 15.3.2, react-native-macos: ^0.10.5
- Using Mac

**Comment by ptmt** [comment]
I suppose that's because they require `react-native` directly https://github.com/aksonov/react-native-router-flux/blob/b11a84962e4e4d9265770382b8859d21d1a12ea0/src/NavBar.js#L37. Unfortunately, there is no good solution right now for aliasing this, only manually change (fork) the library and abstract `react-native`. React Native macOS might be updated as a pluggable thing to react-native in the future to support all third-party plugins.

**Comment by jhen0409** [comment]
@ptmt, maybe we can write a babel plugin to transform `react-native` to `react-native-macos` for import / require? We can add it to [transformer](https://github.com/ptmt/react-native-macos/blob/master/packager/transformer.js#L35) by default. Although there may be have a better way.

**Comment by hmelenok** [comment]
Have the same issue, maybe someone know good router for using with 'react-native-macos'

**Comment by ptmt** [comment]
@hmelenok This going to be resolved with https://github.com/ptmt/react-native-macos/pull/125 by @jhen0409 , you can try it right now and provide a feedback.

**Comment by hmelenok** [comment]
Seems the same now, it not found it in your version of RN 

<img width="1015" alt="screen shot 2016-11-14 at 23 25 11" src="https://cloud.githubusercontent.com/assets/2149114/20283433/b90969d4-aac1-11e6-8a4c-0e883e0bba63.png">

**Comment by hmelenok** [comment]
I had use fork from `git+https://github.com/jhen0409/react-native-desktop.git#patch-2`
`.babelrc`: 
``` json
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "react-native": "react-native-macos",
        },
      }
    ],
  ],
}
```
`.flowconfig`:
``` bash
...
module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'
module.name_mapper='react-native' -> 'react-native-macos'
...
```

seems as alias working but without `Platform`

**Comment by ptmt** [comment]
Added `Platform.select` support in 0.11.0-rc4. PR for babel transforming is still under testing

**Comment by ptmt** [comment]
0.12.0 now have babel-transform plugin
