### ISSUE TITLE
webwiew onShouldStartLoadWithRequest props not work

### ISSUE THREAD

**Issue by coderwin** [ptmt/react-native-macos#126]
OS 10.11.5

I want to postMessage between React Native with webview(eg. jsbridge)，but RN0.32 doesn't support(0.37 supported)，and the onShouldStartLoadWithRequest also doesn't work。

error:
![react-native-macos-webview](https://raw.githubusercontent.com/coderwin/__/master/src/asserts/rnmacos.png)

**Comment by ptmt** [comment]
Thanks for the issue. Fixed partially, `onMessage`/`onShouldStartLoadWithRequest` doesn't work, though, but I'm close.

![screenshot 2016-11-12 14 50 26](https://cloud.githubusercontent.com/assets/1004115/20237568/5e023b78-a8e7-11e6-9d8b-863e1994d36e.png)

**Comment by ptmt** [comment]
Added `onMessage` support also in latest version
