### ISSUE TITLE
Run macos Desktop apps in different mac pc as a standalone file which i build through xcode 

### ISSUE THREAD

**Issue by TheAhmadSharif** [ptmt/react-native-macos#131]
I have run & build a Mac Desktop App (Just Hello World !!! ) though xcode. Then it creates a Hello.app on a specific folder (In my case, according my app name) which is run with the help of react-native cli under a port like 8081.

Now i want to run this simple desktop apps in different Mac PC as standalone without any dependencies. As I know that, react-native is not installed by default. 

In that case what i have to do ?

**Comment by ptmt** [comment]
I really sorry for long awaited answer. You just need to Build -> Archive this project, the same as for React Native for iOS. It will compile without dependencies into single archived binary *.app that can be distributed as a stand-alone file.
