### ISSUE TITLE
Cursor State management

### ISSUE THREAD

**Issue by matpaul** [ptmt/react-native-macos#135]
Hello!
I started implement Cursor state management from Desktop-specific APIs #4

I think it will be Cursor Component with methods like 

```javascript
import {Cursor} from 'react-native-macos';

Cursor.setPointingHand()
Cursor.setArrow();
```
All types: https://developer.apple.com/reference/appkit/nscursor

So what's your vision about component interface ?

**Comment by ptmt** [comment]
Yep, something like that. Look at `StatusBar` for example. It has both imperative static methods https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L229 but also could be used as declarative virtual React component https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L342

So you can do that with Cursor (much simplier, in fact). Consider this:
```jsx
<Cursor type={'arrow'} />
```

Anyway, imperative way to implement would be enough for start.

**Comment by matpaul** [comment]
Okay, i think most use-case is change cursor on hover like link component etc.., so for simplify i will implement imperative way at start. Will attach pull request to this issue. 

Also it will be good tag this type of issues as discussion
