### ISSUE TITLE
Possible to link libraries?

### ISSUE THREAD

**Issue by c-h-** [ptmt/react-native-macos#149]
Hi, really enjoying digging into this project.

I noticed you said it isn't possible to use third party plugins that use native modules.

Would it be possible to link libraries like here? https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

I can drop a library into XCode but it seems like the Build Phases option isn't present for the project.

Is there some way I can try to help to enable this feature? Thanks!

**Comment by ptmt** [comment]
Unfortunately, native libraries which developed for iOS can't be linked to macOS without an effort. What's the plugin that you have tried to link?

**Comment by c-h-** [comment]
@ptmt Thanks for the fast reply.

I tried to link [React Native I18n](https://github.com/AlexanderZaytsev/react-native-i18n).

Really all I need support for getting the user's language. On the web I'd use something like `navigator.language`.

Would you be able to share how I might approach getting that on macOS?

**Comment by skibz** [comment]
here's an example [example](https://github.com/pvinis/ImDoingWhat/blob/master/macos/ImDoingWhat/IDWTimerManager.m)

**Comment by ptmt** [comment]
This would be pretty easy. It doesn't require a platform-specific code, just need to have a new compile target. I'll fork it and demonstrate.
