### ISSUE TITLE
UI Explorer: Failed to build DependencyGraph: @providesModule naming collision:

### ISSUE THREAD

**Issue by axsauze** [ptmt/react-native-macos#154]
I've tried to run the UIExplorer demo.

When trying to build the project I get the following error:

``` bash
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: AppEventsTest
  Paths: /Users/USERNAME/Programming/devnull/react-native-macos/Examples/UIExplorer/react-native/IntegrationTests/AppEventsTest.js collides with /Users/USERNAME/Programming/devnull/react-native-macos/IntegrationTests/AppEventsTest.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: AppEventsTest
  Paths: /Users/USERNAME/Programming/devnull/react-native-macos/Examples/UIExplorer/react-native/IntegrationTests/AppEventsTest.js collides with /Users/USERNAME/Programming/devnull/react-native-macos/IntegrationTests/AppEventsTest.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/USERNAME/Programming/devnull/react-native-macos/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
    at module.getName.then.name (/Users/USERNAME/Programming/devnull/react-native-macos/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:115:31)
~
Process terminated. Press <enter> to close the window
```

I haven't made any modifications to the code, so I wouldn't know what might be causing this issue.

Would you know if there's any dependencies missing that I need to install?

**Comment by ptmt** [comment]
It looks you have `react-native` folder in UIExplorer (`/Users/USERNAME/Programming/devnull/react-native-macos/Examples/UIExplorer/react-native/`). Can you confirm that? If that's true try to delete it.

**Comment by axsauze** [comment]
Hey @ptmt I was just about to reply - you are totally correct, I have deleted the folder and it's now working!

I was quite confused as the README.md in Examples/UIEXplorer says to clone and install react-native.

Thank you for your help by the way!

**Comment by ptmt** [comment]
@axsauze Thanks for pointing out. I see now https://github.com/ptmt/react-native-macos/tree/master/Examples/UIExplorer
 this is an untouched copy from the original Facebook repository.

**Comment by axsauze** [comment]
Ah I see! I was a bit confused with those instructions, I was wondering why on earth would I want to run this on Android and IOS haha - Thanks!
