### ISSUE TITLE
Resize window

### ISSUE THREAD

**Issue by TinchyChing** [ptmt/react-native-macos#161]
How to resize window in react native macos

**Comment by ptmt** [comment]
It's not possible right now, but can be done easily by writing native module. What's your task?

**Comment by jaywcjlove** [comment]
![linux](https://cloud.githubusercontent.com/assets/1680273/25964206/a74342fc-36b6-11e7-867a-e6e7eef5990f.gif)

How is this problem solved? Figure.

@ptmt

**Comment by ptmt** [comment]
@jaywcjlove , not yet. See https://github.com/ptmt/react-native-macos/issues/83

After finishing merging with latest React Native changes: https://github.com/ptmt/react-native-macos/pull/163 I'll probably take a look on resizing problem once again.

**Comment by ptmt** [comment]
First results of new PR look promising. @jaywcjlove, do you have this repository open to do some experiments with it?

**Comment by jaywcjlove** [comment]
@ptmt  I experimented with some methods, Not solved . Have no ability to solve the problem. So I use electron to develop.
Waiting for you to solve. I try again.



https://github.com/jaywcjlove/amac

**Comment by ptmt** [comment]
Electron is absolutely the best way to do it right now. Thanks for the repo, I'll use it as a test case.

**Comment by ptmt** [comment]
Do you have https://github.com/jaywcjlove/amac previous RN version?

**Comment by jaywcjlove** [comment]
@ptmt  https://github.com/jaywcjlove/react-native-macos-amac

**Comment by jaywcjlove** [comment]
@ptmt The new version does not have this problem. thx!
