### ISSUE TITLE
requestIdleCallback not work

### ISSUE THREAD

**Issue by jhen0409** [ptmt/react-native-macos#162]
The `requestIdleCallback` doesn't work on here, I tested in `master` branch.

We can just run `requestIdleCallback(() => alert(1))` for reproduce this issue. Maybe we can include [TimerExample](https://github.com/ptmt/react-native-macos/blob/master/Examples/UIExplorer/js/TimerExample.js#L42) to UIExplorer. (currently not in macos)

**Comment by ptmt** [comment]
Thanks for posting issue. Currently, I'm on syncing with RN upstream, fixing more than 300 merge conflicts and the whole bunch of breaking changes (Yoga, React/ namespace, and hundreds other). Right after this, I'll take a look at this.

**Comment by ptmt** [comment]
I know, i"m probably too late, but this has been fixed in 0.15.2.
