### ISSUE TITLE
update cli to upstream

### ISSUE THREAD

**Issue by Haroenv** [ptmt/react-native-macos#166]
- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

This will make the dependencies download via yarn when available.

**Comment by ptmt** [comment]
work in progress https://github.com/ptmt/react-native-macos/pull/163

**Comment by ptmt** [comment]
Published

**Comment by Haroenv** [comment]
🙌
