### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by sm2017** [ptmt/react-native-macos#167]
1. How can I have a database??
2. Is realm supported??
3. Is sqlite suppoted??

**Comment by ptmt** [comment]
1. Only if you're able to write some native code, unfortunately. 
2. Not directly, this https://github.com/realm/realm-js/tree/master/src/RealmJS.xcodeproj should be updated before using, but I' never have a chance to work with Realm. 
3. Not directly, it also requires writing wrappers in native code (Objective-C or Swift).
