### ISSUE TITLE
Can react-native-macos be published to the mac appstore ?

### ISSUE THREAD

**Issue by rsaccon** [ptmt/react-native-macos#173]
Maybe there are any low level Mac OS apis used which would forbid the store submission, maybe the Appstore terms do not allow such a thing or there is simply something missing in the react-native-macos system to make it work. Anybody knows or has successfully submitted an app ?

**Comment by waylybaye** [comment]
I saw this issue before I start my project and it's still not answered after I have submitted my app to App Store :)

So, yes, the product using react-native-macos can be published to MAS.

**Comment by ptmt** [comment]
wow! So great. Have you been approved? Can you share a link?

**Comment by waylybaye** [comment]
Yes, it has been approved. It's also open source on github: https://github.com/waylybaye/XcodeCleaner

Thanks @ptmt  for your great work!

**Comment by ptmt** [comment]
Your work inspired me to get back on this fork, thank you sir!

**Comment by assertchris** [comment]
Can this issue be closed then?
