### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by kholmatov** [ptmt/react-native-macos#174]
Hi, I had this error:
<hr>
 **BUILD FAILED**<p> 
The following commands produced analyzer issues:
	Analyze /Volumes/HD2/react/MyProject/node_modules/react-native-macos/ReactCommon/yoga/yoga/Yoga.c
	Analyze /Volumes/HD2/react/MyProject/node_modules/react-native-macos/ReactCommon/yoga/yoga/YGNodeList.c
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Volumes/HD2/react/MyProject/macos/unique/React.build/Debug/third-party.build/Objects-normal/x86_64/Bits.o /Volumes/HD2/react/MyProject/node_modules/react-native-macos/third-party/folly-2016.09.26.00/folly/Bits.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Launching build/Build/Products/Debug/MyProject.app
The file /Volumes/HD2/react/MyProject/macos/build/Build/Products/Debug/MyProject.app does not exist.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug/MyProject.app/Contents/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
</p>
<hr>
How fix this problem?

**Comment by ptmt** [comment]
Could you please share more information if it's still relevant to you? (Or someone else who stuck into this)? 

What's the macOS version, have you tried to build RN for iOS, have you tried to build it with Xcode, etc.

**Comment by kholmatov** [comment]
**What's the macOS version:** 
macOS High Sierra

**have you tried to build RN for iOS:** 
yes

**have you tried to build it with Xcode, etc:** 
yes, I tried buld with Xcode 9

**Comment by lndgalante** [comment]
Try this @kholmatov https://github.com/nodejs/node-gyp/issues/569#issuecomment-94917337

**Comment by DeforeChen** [comment]
I run into the same problem. My mac os version is 10.13.2 and even after I've tried the solved way mentioned before, it does not work.[https://github.com/nodejs/node-gyp/issues/569#issuecomment-94917337](url)
