### ISSUE TITLE
Any plan to merge react-native newer version?

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-macos#180]
Last merged react-native version is v44, which use react v16.0.0-alpha.12.
[react v16 rc](https://github.com/facebook/react/issues/10294) supports fragments (returning arrays from components), a long-expected feature.

**Comment by ptmt** [comment]
Sure, I do have plans. There a lot of changes such as metro-bundles (decoupled from react-native packager). React 16 Fiber also is very welcomed. I'm waiting for it to stabilize, and before this work I'm upgrading my casual React Native iOS / Android projects. 

I guess I can close it since, it's a question.

**Comment by beretboat** [comment]
Thanks. Glad to hear.

May I ask when will it happen? In days, weeks, or months? Just a rough estimation, it does not have to be a accurate time.

**Comment by ptmt** [comment]
After 0.50 will be finally released
https://github.com/facebook/react-native/releases I'll try it on my
projects and will start merging I guess (it usually takes 2-5 days). If
it's not ok, or there is a very important feature that I need to wait for
0.52 then, that means +1 month.

**Comment by beretboat** [comment]
Got it. Thanks!

**Comment by beretboat** [comment]
Sorry to reopen this. 0.52 has been released for a while, are you still going to merge this version?

**Comment by ptmt** [comment]
Yes. I started it locally. There a lot of changes, including React 16, metro bundler, revised UIExplorer -> TesterApp, moving from Travis to CircleCI, etc. 2661 files to resolve (some of them are quick and straightforward, but a hundred or so are tricky one).

**Comment by skellock** [comment]
@ptmt Curious if you have a strategy for dealing with this considering you've done this a few times already.  Or are you just the most patient man on the planet?

Is something you could use help with or is this a @ptmt shaped problem?

**Comment by beretboat** [comment]
Good to know, thanks!

**Comment by ptmt** [comment]
@skellock It's good question. I think that there are

**Comment by ptmt** [comment]
This is how it looks. 2500 merge conflicts to resolve. 50% of them really silly and I usually do this stage fast. The rest usually are Git merge fails, and probably most sophisticated merger software will help dramatically. I tried most of the free software available for it. 

Here is a few examples:
![screenshot 2018-01-17 17 26 23](https://user-images.githubusercontent.com/1004115/35047833-3e73e720-fbac-11e7-9510-6a0ec1d68038.png)
(just need to preserve -macos here).

![screenshot 2018-01-17 17 24 18](https://user-images.githubusercontent.com/1004115/35047837-4251d816-fbac-11e7-8e61-462f62d5f392.png)
AppKit doesn't allow to access CGI data, so I need to use a helper. Multiple times. Probably the better solution is to add NSImage method. 

But even so, 10% of the rest conflicts is where you need to really spend time. I'll do pull request as soon as I finish this and when I'll need to set up a new CI (CircleCI) and make it all work. I would mean *a lot* to me if you could test it after pull request is published.
