### ISSUE TITLE
Error when starting a new project

### ISSUE THREAD

**Issue by viniychuk** [ptmt/react-native-macos#181]
### Description

I installed react-native-macos-cli, initialized a new project, it has no problem building but the packager doesn't work so the app wouldn't load.

### Reproduction Steps and Sample Code

Just follow the readme:
```
$ npm install react-native-macos-cli -g
$ react-native-macos init MyProject
$ cd MyProject
$ react-native-macos run-macos
```

Here's the screenshot of the log: http://take.ms/7LaJc.

Then, if I'm just executing `react-native-macos start`, I'm getting a slightly different error:
```
Scanning 595 folders for symlinks in /Users/mounter/www/trill/macos/MyProject/node_modules (7ms)
Looking for JS files in
   /Users/mounter/www/trill/macos/MyProject
   /Users/mounter/www/trill/macos/MyProject 


React packager ready.

Loading dependency graph...2017-11-15 22:07 node[791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-11-15 22:07 node[791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1353:9)
Loading dependency graph...
```
and then it's terminated.

### Additional Information
* react-native-macos-cli: 2.0.1
* react-native-macos: 0.16.0
* react-native-cli: 2.0.1
* Platform: Mac OS 
* Development Operating System: MacOS High SIerra
* Dev tools: XCode (but was running from the terminal)

**Comment by ptmt** [comment]
It looks like the Watchman error, see 
 for details: http://facebook.github.io/watchman/docs/troubleshooting.html#fsevents. Let me know if  it helps.

**Comment by viniychuk** [comment]
Thanks @ptmt ,

```
watchman shutdown-server 
brew update 
brew reinstall watchman
```

did the trick.
