### ISSUE TITLE
Dimensions.addEventListener does not function

### ISSUE THREAD

**Issue by jtag05** [ptmt/react-native-macos#187]
### Description

`Dimensions.addEventListener` method does not fire on window resize.

### Reproduction Steps and Sample Code

```
import { Dimensions } from 'react-native';

const handler = (dims) => {
    console.log(dims); // Never called
}

Dimensions.addEventListener('change', handler);
```
### Solution

I have yet to dive into what might be causing this issue but I'll begin to debug.

### Additional Information

* React Native version: (macos) 0.16.1
* Development Operating System: MacOS 10.13.3

**Comment by shirakaba** [comment]
I've found that the `Dimensions.get("window")` just returns the full screen size rather than the size of the window. Probably related..!

**Comment by ptmt** [comment]
@shirakaba you were right! Sorry took me so long. Finally got time to fix minor issues.

**Comment by ptmt** [comment]
![aug-06-2018 21-06-54](https://user-images.githubusercontent.com/1004115/43733429-4d0037d0-99bd-11e8-8383-b639f86318be.gif)
