### ISSUE TITLE
Invoke shell command

### ISSUE THREAD

**Issue by mirkods** [ptmt/react-native-macos#190]
Hi there, how can I invoke a shell command on my mac?

Mirko

**Comment by ptmt** [comment]
You'll need to add a native module. This is an example:
https://github.com/ptmt/ratpack/commit/d1c2b2e90228f63629bb8714c4b941a9411a2438

Let me know if I can help you to setup in your project

**Comment by mirkods** [comment]
Thanks for you response @ptmt, I haven't experience with the native module if you can help me will be fine

**Comment by mirkods** [comment]
After some tests looking for your module I implemented my first native module 👍 Thanks for your example @ptmt
