### ISSUE TITLE
0.52.2 Finishing touches

### ISSUE THREAD

**Issue by Pagebakers** [ptmt/react-native-macos#200]
Not sure where to put this since the PR has been merged into master, so here goes :)

Last things I'm running into:

- [x] ListView doesn't scroll
- [ ] Loading images with require('Image.png') doesn't work
This seems to be an issue on dev build only though.

- [ ] Padding doesn't work on TextInput
I looked into rewriting RCTTextField to RCTSingleLineTextField, but I don't know enough about Mac development nor do I have enough time to figure this out.

Other then that things seem to run pretty solid here!

**Comment by ptmt** [comment]
Thanks for the feedback. Could you try to replace ListView with FlatList?

**Comment by unmec** [comment]
FlatList doesn't scroll when click and drag, but it works when using gestures.

**Comment by aleclarson** [comment]
@unmec Why do you expect "click+drag to scroll" behavior in a desktop application? I've never seen anyone do that.

**Comment by unmec** [comment]
@aleclarson Well I believe you certainly have. Just image what would you do when you want to select a big piece of text in Safari? Click, then drag to scroll to when it ends right?

**Comment by aleclarson** [comment]
@unmec Ah, you didn't mention text selection in the previous comment. Can you open a new issue for that, please?
