### ISSUE TITLE
babel-plugin-module-resolver missing from devDependencies. "Unknown plugin module-resolver"

### ISSUE THREAD

**Issue by ethanx94** [ptmt/react-native-macos#205]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. react-native-macos init MyProject

### Expected Behavior

Metro bundler should compile.

### Actual Behavior

error: bundling failed: ReferenceError: Unknown plugin "module-resolver" specified in "[MYPROJECT]/.babelrc" at 0,

### Reproducible Demo

Just init a new project.
We need something in the init scripts like
`yarn add -D babel-plugin-module-resolver`
3.1.1 installed automatically and works for me.

**Comment by ptmt** [comment]
Fixed in the latest release

**Comment by ptmt** [comment]
Thanks for the feedback! It was a very silly mistake. It handled only npm setups, not yarn.

**Comment by ethanx94** [comment]
Much appreciated!
