### ISSUE TITLE
UIExplorer: Rotate transforms not working on macOS 10.14

### ISSUE THREAD

**Issue by brunolemos** [ptmt/react-native-macos#206]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.14 Beta
    Node:  8.11.1
    Yarn:  1.7.0
    npm:  6.1.0
    Watchman:  4.90
    Xcode:  Xcode 10 
    Android Studio:  3.1

  Packages: (wanted => installed)
    react-native: 0.56
    react: 16.4

  Target Platform: macOS (10.4)

### Steps to Reproduce

1. Open UIExplorer
2. Open Transforms tab

<img width="461" alt="image" src="https://user-images.githubusercontent.com/619186/42727644-3fe6c65c-8781-11e8-84cb-70841fef1283.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/619186/42727648-4976a4b2-8781-11e8-9ec7-9ccd5d69fbf9.png">

**Comment by Pagebakers** [comment]
Can't get this to work on 10.13.6 either.

Also the anchor points for libart are being reset to 0.0, so it's not possible to animate from the center point.

These two issues are related to High Sierra's stricter view layer policy.

**Comment by ptmt** [comment]
Added a workaround for `0.18.0-alpha.7`

**Comment by ex3ndr** [comment]
in alpha.6 there are still a problems with scaleY: -1. It seems it uses zero anchor points instead of a center.

**Comment by ptmt** [comment]
Could you combine that with translate? Anyway I think it could be fixed in the core, if it's default RN iOS behavior
