### ISSUE TITLE
Stretch RCTRootView to fill its native parent view

### ISSUE THREAD

**Issue by aleclarson** [ptmt/react-native-macos#218]
Curious if anyone has tackled this before.

I've tried doing it with Javascript, to no avail. Seems like the component that I return from the `AppRegistry.registerComponent` callback must have its size manually synchronized on the native side. Is this true? Or _should_ I be able to use `width: '100%'` on my registered `AppRegistry` component?

Note: The `contentView` of my `RCTRootView` __does__ fill the available space, but the component I return from `AppRegistry.registerComponent` doesn't want to do the same.

Oh, and I'm using `RCTRootViewSizeFlexibilityWidthAndHeight`.

**Comment by aleclarson** [comment]
Looks like `RCTRootViewSizeFlexibilityWidthAndHeight` was the issue. 😓

**Comment by unmec** [comment]
Hi @aleclarson , just had similar question about this. Could you please elaborate a bit more how you achieved it? It seems that the dimension state will not change when manually drag window's edges around. Thanks!

**Comment by aleclarson** [comment]
IIRC, the solution was to not set the `sizeFlexibility` property of `RCTRootContentView` to `RCTRootViewSizeFlexibilityWidthAndHeight` if you want your top-level React component to fill the available space.

> It seems that the dimension state will not change when manually drag window's edges around.

Are you speaking of [this API](https://facebook.github.io/react-native/docs/dimensions) specifically? I haven't tried using that yet.

**Comment by unmec** [comment]
@aleclarson Yes I was referring to that API. I was playing around with an existing RN project for iOS to find out which parts work well with macos and which parts don't. Apparently dimensions doesn't for now.

**Comment by aleclarson** [comment]
@unmec Okay, please open an issue for that specifically, with the expected behavior versus the actual behavior. Thanks!
