### ISSUE TITLE
PickerIOS component is not rendered

### ISSUE THREAD

**Issue by maxceem** [ptmt/react-native-macos#219]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS 10.14.2
  Node: 8.12.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: Not Found

### Steps to Reproduce

`<PickerIOS>` component is not rendered.

![image](https://user-images.githubusercontent.com/146016/50502983-59402f80-0a9e-11e9-8f74-4c15d35d5142.png)

1. Clone this repository.
2. Open project `RNTester/RNTester.xcodeproj` in XCode and run it.
3. On the left side menu click **AyncStorage**.
4. On the right side, right under **Basics - getItem, setItem, removeItem** `<PickerIOS>` component has to be rendered, but it's not.

### Expected Behavior

In the README there is link to compiled **UIExample** which can be donwloaded the [link](https://github.com/ptmt/react-native-macos/files/199128/UIExplorer.zip).

If we run it, and navigate to **AyncStorage** example, we can see that `<PickerIOS>` compnent is rendered here, even not perfectly:

![image](https://user-images.githubusercontent.com/146016/50503071-0a46ca00-0a9f-11e9-870f-fc550a6de314.png)

### Actual Behavior

See, steps to reproduce.

### Reproducible Demo

See, steps to reproduce.

### Notes

- I've tried to use `<PickerIOS>` component outside of `RNTester` project it also is not rendered.
- There is related issue [Picker component unimplemented](https://github.com/ptmt/react-native-macos/issues/202). But that issue about `<Picker>` component not `<PickerIOS>`.

**Comment by aleclarson** [comment]
The name "IOS" in `<PickerIOS>` implies an iOS-only native component. Since this is a macOS-focused fork of React Native, it's not possible to support this.
