### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by ozgrozer** [ptmt/react-native-macos#220]
I'm seeing the latest commit was 4 months ago. So should I start developing something with React Native MacOS or should I look for something else for native MacOS apps?

**Comment by LukasBombach** [comment]
Too bad I really liked this project, but i know it's a beast. Glad you held on to this for so long 👌 

props for github.com/desktopui

**Comment by elmehalawi** [comment]
Same, this looked like a great alternative to building xib files in that shitty drag and drop editor. Thanks for all your work though.

**Comment by aleclarson** [comment]
[Microsoft/react-native-macos](https://github.com/Microsoft/react-native-macos) may be a valid alternative. Not sure what its current status is.

**Comment by eveningkid** [comment]
@aleclarson do you have any idea how to give it a try? I'm not so sure they did something with this repo...

**Comment by aleclarson** [comment]
@eveningkid After a closer look, the `0.51-macos` branch has all of the macOS-related changes. See here: https://github.com/facebook/react-native/compare/0.51-stable...Microsoft:0.51-macos

But the Issues tab isn't enabled, and they haven't touched it since July 2018, so it's probably not your best bet. 😅

**Comment by ozgrozer** [comment]
I've found [Proton Native](https://github.com/kusti8/proton-native). Looks like it does the same job like this repo, cross platform native apps with React Native. Did anyone try it?

**Comment by LukasBombach** [comment]
Oh that's cool, I did not know proton. There is also https://github.com/parro-it/libui-node and there are also projects implementing react bindings for that

**Comment by LukasBombach** [comment]
Oh I just saw that Proton Native as well as  libui-node, as well as https://github.com/mimecorg/vuido all build on top of libui, see https://github.com/andlabs/libui#language-bindings

**Comment by ptmt** [comment]
I'd say Proton-native is quite different in many ways, but yeah, it's
libui-based so pros and cons are similar. There are other interesting
projects: node-webrender, for instance. I'll try to setup a web-site for
github.com/desktopui with the list of those, contributions are welcome!

**Comment by ozgrozer** [comment]
I just made a hello world app in Proton Native for MacOS and the .app file size is 53.1 mb. And node-webrender looks cool.

**Comment by LukasBombach** [comment]
> I'd say Proton-native is quite different in many ways, but yeah, it's libui-based so pros and cons are similar. There are other interesting projects: node-webrender, for instance. I'll try to setup a web-site for github.com/desktopui with the list of those, contributions are welcome!

I really like this, I was also dabbling around with something like this, gathering info on the many ways you can build native desktop apps with JS. Can you share your Figma Mockup as a basis to create desktop apps with those different libraries? I guess you have something like https://hnpwa.com/ in mind, if you had a public mockup others could join in.

**Comment by ptmt** [comment]
@ericvicenti that gives us hope, thanks for sharing!

@LukasBombach Here it is https://www.figma.com/file/CfI5xukm95XQR9H88PTtKyii/Chat-app?node-id=0%3A1.
Figma mockup here is really simple, just a basic Slack layout, although the app itself has some challenges such as inverted and virtualized ScrollView, or animation. When Electron version is finished, you can download and play it. 

If you want to try to implement it in Proton-Native or any other framework just for fun let me know, I'll make you a contributor to https://github.com/desktopui/silver-bullet (it's a working title :)). I'll try to help as much as can, we can exchange React components, for example. 

> hnpwas

Sure is https://desktopui.github.io/silver-bullet//pwa/! Sorry, web-site is still a mess. I did one desktop PWA a year ago, and was impressed (and not just by how hard invalide ServiceWorkers properly :) ). Want to give it another try. 

My roadmap: Playing more with Nuklear - (C GUI Toolkit in single .h file), Revery and webrender from Mozilla. I'll add 10 more frameworks on the web-site, maybe just posting links would be useful for somebody.

**Comment by aleclarson** [comment]
Anyone that wants to use React hooks with `react-native-macos`, please provide feedback on #226, which is a stepping stone towards the next stable React version (v16.8.0). Thanks!
