### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by jimberlage** [ptmt/react-native-macos#222]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Subject

Could a new version of this be published to NPM?  (If you have the time, of course, there's no immediate rush.) A bug I just posted a patch for blocks me.  Thanks for all your work on this project, it's awesome!

**Comment by ptmt** [comment]
Published as 0.18.2 https://www.npmjs.com/package/react-native-macos/v/0.18.2

Thanks again!
