### ISSUE TITLE
Failing CI - Travis CI not configured

### ISSUE THREAD

**Issue by DanielRuf** [ptmt/react-native-macos#243]
## 🐛 Bug Report

The CI is failing because Travis CI is not configured. 
See https://travis-ci.org/ptmt/react-native-macos/builds/519953793#L445

We should add a `.travis.yml` and run `jest`.

**Comment by ptmt** [comment]
To run all tests properly it requires some work right now, I'd love to do
it but have no energy at the moment.

>

**Comment by DanielRuf** [comment]
I will check this when I find some time and try to provide a PR.
