### ISSUE TITLE
command not found: react-native-macos

### ISSUE THREAD

**Issue by thuanphamdev** [ptmt/react-native-macos#249]
## 🐛 Bug Report

zsh: command not found: react-native-macos

## Expected Behavior

I installed npm install 

> react-native-macos-cli -g

and I started the project with the 

> react-native-macos init RNMacos command

then the message 

> zsh: command not found: react-native-macos will appear

Show me how to fix it. Thank you very much.

## Minimal Reproduction

(For bugs that cannot be reproduced within RNTester, please provide a [minimal](https://stackoverflow.com/help/mcve) repository.)

## Environment

- macOS v10.x.x
- react-native-macos v0.x.x

**Comment by danieltillero** [comment]
How did you fix this error?
