### ISSUE TITLE
Move to proper Github organization / rename project

### ISSUE THREAD

**Issue by ptmt** [ptmt/react-native-macos#61]
https://github.com/ReactNativeDesktop could be irrelevant since it's not about desktop in common sense now (or yet).

**Comment by geuis** [comment]
Might want to hold off for a bit, given that Facebook has announced the equivalent of React Native for Windows. It won't surprise me to see a version for Mac and Linux soon.

**Comment by ptmt** [comment]
moved to react-native-macos
