### ISSUE TITLE
@ptmt List of issues that need to be worked on?

### ISSUE THREAD

**Issue by geuis** [ptmt/react-native-macos#78]
Beyond you just filing tons of issues for things that need to get done, could you brain dump a list of everything that needs doing? I'm thinking of anything ranging from documentation to low level obj-c stuff. There might be some things I can help out with while you're working on the hardcore parts.

**Comment by ptmt** [comment]
Great to hear! It would be really appreciated! It depends on how much time you have and what's your personal most wanted features. Mostly, you can just search the source code for `TODO:` and get a lot of unimplemented things, then we can get a quick discussion about it.

**Comment by buhe** [comment]
Awesome project!
I create a NativeBase fork ( https://github.com/buhe/NativeBaseDesktop ), Hope to be helpful.
Here is TODO List.
- [ ] Text backgroupcolor
- [ ] Icon Test
- [ ] Input Style

**Comment by ptmt** [comment]
Duplicate, See #4
