### ISSUE TITLE
Callback associated with button in Alert.alert not working

### ISSUE THREAD

**Issue by nunobbras** [ptmt/react-native-macos#85]
Hi, I am trying to use the callback from a button in an alert. For instance the RN tutorial 

```
Alert.alert(
  'Alert Title',
  'My Alert Msg',
  [
    {text: 'Ask me later', onPress: () => console.log('Ask me later pressed')},
    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
    {text: 'OK', onPress: () => console.log('OK Pressed')},
  ]
)
```

For some reason the callbacks associated with the onPress are not called. 
I tried to understand where are the bindings for the Cocoa but I didn't found any problem.

thanks

**Comment by ptmt** [comment]
Yeah, sorry, I didn't have a chance to adopt these callbacks yet. Will try to fix in next release.

**Comment by nunobbras** [comment]
Ok. Thanks for the quick feedback. Where is it supposed to be handle?

**Comment by nunobbras** [comment]
Hmm.. got it thanks

**Comment by ptmt** [comment]
Sorry for not answering, have you managed to fix the issue? Do you mind to send a pull request?

**Comment by nunobbras** [comment]
No, I just left this for later... but I will pick it in a few days. Have a Demo with RND in a week...
I will send a pull request if I have time to solve it conveniently.

**Comment by ptmt** [comment]
@nunobbras glad to hear! Don't hesitate to DM me to ask any questions on Discord / Twitter or email.

**Comment by nunobbras** [comment]
OK, thanks for the support!
