### ISSUE TITLE
Support for video element

### ISSUE THREAD

**Issue by diogoviannaaraujo** [ptmt/react-native-macos#96]
Is there any planned support for a video element? should it be/does existst a vlc/ffmpeg native component for desktop? Or the correct way should be throu a webview?

**Comment by knoopx** [comment]
I've done some progress a long time ago, I can push what I got but is half-cooked and needs further work.

**Comment by ptmt** [comment]
can it be a plugin?

**Comment by ptmt** [comment]
Closing this, it sounds better as a plugin like react-native-video.
